### ISSUE TITLE
[BUG] Attempt to send via SES sender cause fatal error on v3.1.0

### ISSUE THREAD

**Issue by ikorchynskyi** [opensearch-project/notifications#1053]
**What is the bug?**

Attempt to send via SES sender cause fatal error on Opensearhc v3.1.0:

```
{"type": "server", "timestamp": "2025-07-19T16:28:11,490Z", "level": "ERROR", "component": "o.o.b.OpenSearchUncaughtExceptionHandler", "cluster.name": "opensearch-cluster", "node.name": "opensearch-node", "message": "fatal error in thread [DefaultDispatcher-worker-1], exiting", "cluster.uuid": "idtMdBc8QAS3pM-h5M795w", "node.id": "NKrKnKlsTl27Cjw_phJoEA" ,
"stacktrace": ["java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.http.AmazonHttpClient",
"at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:236) ~[aws-java-sdk-core-1.12.687.jar:?]",
"at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:225) ~[aws-java-sdk-core-1.12.687.jar:?]",
"at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(AWSSecurityTokenServiceClient.java:299) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(AWSSecurityTokenServiceClient.java:285) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:61) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:27) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46) ~[aws-java-sdk-core-1.12.687.jar:?]",
"at org.opensearch.notifications.core.credentials.oss.CredentialsProviderFactory.getCredentialsProviderByIAMRole(CredentialsProviderFactory.kt:30) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at org.opensearch.notifications.core.credentials.oss.CredentialsProviderFactory.getCredentialsProvider(CredentialsProviderFactory.kt:20) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at org.opensearch.notifications.core.credentials.oss.SesClientFactoryImpl.createSesClient$lambda$0(SesClientFactoryImpl.kt:19) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at java.base/java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]",
"at org.opensearch.notifications.core.utils.SecurityAccess.doPrivileged(SecurityAccess.kt:25) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at org.opensearch.notifications.core.credentials.oss.SesClientFactoryImpl.createSesClient(SesClientFactoryImpl.kt:17) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at org.opensearch.notifications.core.client.DestinationSesClient.sendMimeMessage(DestinationSesClient.kt:88) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at org.opensearch.notifications.core.client.DestinationSesClient.execute(DestinationSesClient.kt:74) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at org.opensearch.notifications.core.transport.SesDestinationTransport.sendMessage(SesDestinationTransport.kt:43) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at org.opensearch.notifications.core.transport.SesDestinationTransport.sendMessage(SesDestinationTransport.kt:23) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at org.opensearch.notifications.core.NotificationCoreImpl.sendMessage$lambda$0(NotificationCoreImpl.kt:38) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at java.base/java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]",
"at org.opensearch.notifications.core.NotificationCoreImpl.sendMessage(NotificationCoreImpl.kt:35) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"at org.opensearch.notifications.send.SendMessageActionHelper.sendMessageThroughSpi(SendMessageActionHelper.kt:598) ~[?:?]",
"at org.opensearch.notifications.send.SendMessageActionHelper.sendEmailFromSesAccount(SendMessageActionHelper.kt:566) ~[?:?]",
"at org.opensearch.notifications.send.SendMessageActionHelper.access$sendEmailFromSesAccount(SendMessageActionHelper.kt:63) ~[?:?]",
"at org.opensearch.notifications.send.SendMessageActionHelper$sendEmailMessage$1$statusDeferredList$1$1.invokeSuspend(SendMessageActionHelper.kt:479) ~[?:?]",
"at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.9.25.jar:1.9.25-release-852]",
"at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"Suppressed: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.http.AmazonHttpClient",
"\tat com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:236) ~[aws-java-sdk-core-1.12.687.jar:?]",
"\tat com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:225) ~[aws-java-sdk-core-1.12.687.jar:?]",
"\tat com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(AWSSecurityTokenServiceClient.java:299) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"\tat com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(AWSSecurityTokenServiceClient.java:285) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"\tat com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:61) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"\tat com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:27) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"\tat com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46) ~[aws-java-sdk-core-1.12.687.jar:?]",
"\tat org.opensearch.notifications.core.credentials.oss.CredentialsProviderFactory.getCredentialsProviderByIAMRole(CredentialsProviderFactory.kt:30) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.credentials.oss.CredentialsProviderFactory.getCredentialsProvider(CredentialsProviderFactory.kt:20) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.credentials.oss.SesClientFactoryImpl.createSesClient$lambda$0(SesClientFactoryImpl.kt:19) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]",
"\tat org.opensearch.notifications.core.utils.SecurityAccess.doPrivileged(SecurityAccess.kt:25) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
fatal error in thread [DefaultDispatcher-worker-1], exiting
"\tat org.opensearch.notifications.core.credentials.oss.SesClientFactoryImpl.createSesClient(SesClientFactoryImpl.kt:17) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.client.DestinationSesClient.sendMimeMessage(DestinationSesClient.kt:88) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.client.DestinationSesClient.execute(DestinationSesClient.kt:74) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.transport.SesDestinationTransport.sendMessage(SesDestinationTransport.kt:43) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.transport.SesDestinationTransport.sendMessage(SesDestinationTransport.kt:23) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.NotificationCoreImpl.sendMessage$lambda$0(NotificationCoreImpl.kt:38) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]",
"\tat org.opensearch.notifications.core.NotificationCoreImpl.sendMessage(NotificationCoreImpl.kt:35) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.send.SendMessageActionHelper.sendMessageThroughSpi(SendMessageActionHelper.kt:598) ~[?:?]",
"\tat org.opensearch.notifications.send.SendMessageActionHelper.sendEmailFromSesAccount(SendMessageActionHelper.kt:566) ~[?:?]",
"\tat org.opensearch.notifications.send.SendMessageActionHelper.access$sendEmailFromSesAccount(SendMessageActionHelper.kt:63) ~[?:?]",
"\tat org.opensearch.notifications.send.SendMessageActionHelper$sendEmailMessage$1$statusDeferredList$1$1.invokeSuspend(SendMessageActionHelper.kt:479) ~[?:?]",
"\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.9.25.jar:1.9.25-release-852]",
"\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"\tat kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/apache/http/conn/routing/HttpRoutePlanner [in thread \"DefaultDispatcher-worker-2\"]",
"\tat com.amazonaws.http.AmazonHttpClient.<clinit>(AmazonHttpClient.java:165) ~[?:?]",
"\t... 30 more",
"Suppressed: java.lang.NoClassDefFoundError: org/apache/http/conn/routing/HttpRoutePlanner",
"\tat com.amazonaws.http.AmazonHttpClient.<clinit>(AmazonHttpClient.java:165) ~[aws-java-sdk-core-1.12.687.jar:?]",
"\tat com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:236) ~[aws-java-sdk-core-1.12.687.jar:?]",
"\tat com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:225) ~[aws-java-sdk-core-1.12.687.jar:?]",
"\tat com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(AWSSecurityTokenServiceClient.java:299) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"\tat com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(AWSSecurityTokenServiceClient.java:285) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"\tat com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:61) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"\tat com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:27) ~[aws-java-sdk-sts-1.12.687.jar:?]",
"\tat com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46) ~[aws-java-sdk-core-1.12.687.jar:?]",
"\tat org.opensearch.notifications.core.credentials.oss.CredentialsProviderFactory.getCredentialsProviderByIAMRole(CredentialsProviderFactory.kt:30) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.credentials.oss.CredentialsProviderFactory.getCredentialsProvider(CredentialsProviderFactory.kt:20) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.credentials.oss.SesClientFactoryImpl.createSesClient$lambda$0(SesClientFactoryImpl.kt:19) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]",
"\tat org.opensearch.notifications.core.utils.SecurityAccess.doPrivileged(SecurityAccess.kt:25) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.credentials.oss.SesClientFactoryImpl.createSesClient(SesClientFactoryImpl.kt:17) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.client.DestinationSesClient.sendMimeMessage(DestinationSesClient.kt:88) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.client.DestinationSesClient.execute(DestinationSesClient.kt:74) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.transport.SesDestinationTransport.sendMessage(SesDestinationTransport.kt:43) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.transport.SesDestinationTransport.sendMessage(SesDestinationTransport.kt:23) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.core.NotificationCoreImpl.sendMessage$lambda$0(NotificationCoreImpl.kt:38) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]",
"\tat org.opensearch.notifications.core.NotificationCoreImpl.sendMessage(NotificationCoreImpl.kt:35) ~[opensearch-notifications-core-3.1.0.0.jar:3.1.0.0]",
"\tat org.opensearch.notifications.send.SendMessageActionHelper.sendMessageThroughSpi(SendMessageActionHelper.kt:598) ~[?:?]",
"\tat org.opensearch.notifications.send.SendMessageActionHelper.sendEmailFromSesAccount(SendMessageActionHelper.kt:566) ~[?:?]",
"\tat org.opensearch.notifications.send.SendMessageActionHelper.access$sendEmailFromSesAccount(SendMessageActionHelper.kt:63) ~[?:?]",
"\tat org.opensearch.notifications.send.SendMessageActionHelper$sendEmailMessage$1$statusDeferredList$1$1.invokeSuspend(SendMessageActionHelper.kt:479) ~[?:?]",
"\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.9.25.jar:1.9.25-release-852]",
"\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"\tat kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]",
"Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.routing.HttpRoutePlanner",
"\tat java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]",
"\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]",
"\tat java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872) ~[?:?]",
"\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]",
"\t... 31 more",
"Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/apache/http/conn/routing/HttpRoutePlanner [in thread \"DefaultDispatcher-worker-2\"]",
"at com.amazonaws.http.AmazonHttpClient.<clinit>(AmazonHttpClient.java:165) ~[?:?]",
"... 30 more"] }
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.http.AmazonHttpClient
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:236)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:225)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(AWSSecurityTokenServiceClient.java:299)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(AWSSecurityTokenServiceClient.java:285)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:61)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:27)
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
        at org.opensearch.notifications.core.credentials.oss.CredentialsProviderFactory.getCredentialsProviderByIAMRole(CredentialsProviderFactory.kt:30)
        at org.opensearch.notifications.core.credentials.oss.CredentialsProviderFactory.getCredentialsProvider(CredentialsProviderFactory.kt:20)
        at org.opensearch.notifications.core.credentials.oss.SesClientFactoryImpl.createSesClient$lambda$0(SesClientFactoryImpl.kt:19)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
        at org.opensearch.notifications.core.utils.SecurityAccess.doPrivileged(SecurityAccess.kt:25)
        at org.opensearch.notifications.core.credentials.oss.SesClientFactoryImpl.createSesClient(SesClientFactoryImpl.kt:17)
        at org.opensearch.notifications.core.client.DestinationSesClient.sendMimeMessage(DestinationSesClient.kt:88)
        at org.opensearch.notifications.core.client.DestinationSesClient.execute(DestinationSesClient.kt:74)
        at org.opensearch.notifications.core.transport.SesDestinationTransport.sendMessage(SesDestinationTransport.kt:43)
        at org.opensearch.notifications.core.transport.SesDestinationTransport.sendMessage(SesDestinationTransport.kt:23)
        at org.opensearch.notifications.core.NotificationCoreImpl.sendMessage$lambda$0(NotificationCoreImpl.kt:38)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at org.opensearch.notifications.core.NotificationCoreImpl.sendMessage(NotificationCoreImpl.kt:35)
        at org.opensearch.notifications.send.SendMessageActionHelper.sendMessageThroughSpi(SendMessageActionHelper.kt:598)
        at org.opensearch.notifications.send.SendMessageActionHelper.sendEmailFromSesAccount(SendMessageActionHelper.kt:566)
        at org.opensearch.notifications.send.SendMessageActionHelper.access$sendEmailFromSesAccount(SendMessageActionHelper.kt:63)
        at org.opensearch.notifications.send.SendMessageActionHelper$sendEmailMessage$1$statusDeferredList$1$1.invokeSuspend(SendMessageActionHelper.kt:479)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.http.AmazonHttpClient
                ... 30 more
        Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/apache/http/conn/routing/HttpRoutePlanner [in thread "DefaultDispatcher-worker-2"]
                at com.amazonaws.http.AmazonHttpClient.<clinit>(AmazonHttpClient.java:165)
                ... 30 more
        Suppressed: java.lang.NoClassDefFoundError: org/apache/http/conn/routing/HttpRoutePlanner
                at com.amazonaws.http.AmazonHttpClient.<clinit>(AmazonHttpClient.java:165)
                ... 30 more
        Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.routing.HttpRoutePlanner
                at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
                at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
                ... 31 more
Caused by: [CIRCULAR REFERENCE: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/apache/http/conn/routing/HttpRoutePlanner [in thread "DefaultDispatcher-worker-2"]]
```

**How can one reproduce the bug?**
1. Setup and activate a notification via SES sender (I've used snapshot management notifications)
2. Wait till snapshot being created OR press `Send test message` on `Notification channels / Channels` page
3. See error in dead node log

**What is the expected behavior?**

**What is your host/environment?**
 - OS: Linux
 - Version: 3.1.0
 - Plugins:
```
opensearch-alerting                  3.1.0.0
opensearch-anomaly-detection         3.1.0.0
opensearch-asynchronous-search       3.1.0.0
opensearch-cross-cluster-replication 3.1.0.0
opensearch-custom-codecs             3.1.0.0
opensearch-flow-framework            3.1.0.0
opensearch-geospatial                3.1.0.0
opensearch-index-management          3.1.0.0
opensearch-job-scheduler             3.1.0.0
opensearch-knn                       3.1.0.0
opensearch-ltr                       3.1.0.0
opensearch-ml                        3.1.0.0
opensearch-neural-search             3.1.0.0
opensearch-notifications             3.1.0.0
opensearch-notifications-core        3.1.0.0
opensearch-observability             3.1.0.0
opensearch-performance-analyzer      3.1.0.0
opensearch-reports-scheduler         3.1.0.0
opensearch-search-relevance          3.1.0.0
opensearch-security                  3.1.0.0
opensearch-security-analytics        3.1.0.0
opensearch-skills                    3.1.0.0
opensearch-sql                       3.1.0.0
opensearch-system-templates          3.1.0.0
opensearch-ubi                       3.1.0.0
query-insights                       3.1.0.0
repository-s3                        3.1.0
```

**Do you have any screenshots?**
No.

**Do you have any additional context?**
In #1020 both dependencies `org.apache.httpcomponents:httpclient:4.5.14` and  `org.apache.httpcomponents.client5:httpclient5:5.4.2` were added, and I suspect that latter may not be compartible with AWS SDK v1.x

**Comment by SammyROCK** [comment]
I'm suffering from this issue.
After an upgraded from v2.19.1 to v3.1.0, my nodes started to crash every time a monitor would trigger a SES notification.
I had to disable the notification plugin to get it running again.

**Comment by entropical** [comment]
We have a similar error, but with SNS, not SES. Also OS 3.1.

```
May 28 06:45:36 cold2 opensearch[2558879]: fatal error in thread [DefaultDispatcher-worker-2], exiting
May 28 06:45:36 cold2 opensearch[2558879]: java.lang.NoClassDefFoundError: org/apache/http/conn/ConnectionKeepAliveStrategy
May 28 06:45:36 cold2 opensearch[2558879]:         at com.amazonaws.http.AmazonHttpClient.<clinit>(AmazonHttpClient.java:165)
May 28 06:45:36 cold2 opensearch[2558879]:         at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:236)
May 28 06:45:36 cold2 opensearch[2558879]:         at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:225)
May 28 06:45:36 cold2 opensearch[2558879]:         at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(AWSSecurityTokenServiceClient.java:299)
May 28 06:45:36 cold2 opensearch[2558879]:         at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(AWSSecurityTokenServiceClient.java:285)
May 28 06:45:36 cold2 opensearch[2558879]:         at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:61)
May 28 06:45:36 cold2 opensearch[2558879]:         at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:27)
May 28 06:45:36 cold2 opensearch[2558879]:         at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.core.credentials.oss.CredentialsProviderFactory.getCredentialsProviderByIAMRole(CredentialsProviderFactory.kt:30)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.core.credentials.oss.CredentialsProviderFactory.getCredentialsProvider(CredentialsProviderFactory.kt:20)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.core.credentials.oss.SnsClientFactoryImpl.createSnsClient$lambda$0(SnsClientFactoryImpl.kt:20)
May 28 06:45:36 cold2 opensearch[2558879]:         at java.base/java.security.AccessController.doPrivileged(AccessController.java:251)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.core.utils.SecurityAccess.doPrivileged(SecurityAccess.kt:25)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.core.credentials.oss.SnsClientFactoryImpl.createSnsClient(SnsClientFactoryImpl.kt:18)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.core.client.DestinationSnsClient.execute(DestinationSnsClient.kt:48)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.core.transport.SnsDestinationTransport.sendMessage(SnsDestinationTransport.kt:41)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.core.transport.SnsDestinationTransport.sendMessage(SnsDestinationTransport.kt:21)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.core.NotificationCoreImpl.sendMessage$lambda$0(NotificationCoreImpl.kt:38)
May 28 06:45:36 cold2 opensearch[2558879]:         at java.base/java.security.AccessController.doPrivileged(AccessController.java:74)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.core.NotificationCoreImpl.sendMessage(NotificationCoreImpl.kt:35)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.send.SendMessageActionHelper.sendMessageThroughSpi(SendMessageActionHelper.kt:598)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.send.SendMessageActionHelper.sendSNSMessage(SendMessageActionHelper.kt:584)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.send.SendMessageActionHelper.sendMessageToChannel(SendMessageActionHelper.kt:250)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.send.SendMessageActionHelper.access$sendMessageToChannel(SendMessageActionHelper.kt:63)
May 28 06:45:36 cold2 opensearch[2558879]:         at org.opensearch.notifications.send.SendMessageActionHelper$sendMessagesInParallel$1$statusDeferredList$1$1.invokeSuspend(SendMessageActionHelper.kt:160)
May 28 06:45:36 cold2 opensearch[2558879]:         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
May 28 06:45:36 cold2 opensearch[2558879]:         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
May 28 06:45:36 cold2 opensearch[2558879]:         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
May 28 06:45:36 cold2 opensearch[2558879]:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
May 28 06:45:36 cold2 opensearch[2558879]:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
May 28 06:45:36 cold2 opensearch[2558879]:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
May 28 06:45:36 cold2 opensearch[2558879]: Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.ConnectionKeepAliveStrategy
May 28 06:45:36 cold2 opensearch[2558879]:         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:349)
May 28 06:45:36 cold2 opensearch[2558879]:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:557)
May 28 06:45:36 cold2 opensearch[2558879]:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
May 28 06:45:36 cold2 opensearch[2558879]:         ... 31 more
May 28 06:45:38 cold2 systemd[1]: opensearch.service: Main process exited, code=exited, status=1/FAILURE
May 28 06:45:38 cold2 systemd[1]: opensearch.service: Failed with result 'exit-code'.
May 28 06:45:38 cold2 systemd[1]: opensearch.service: Consumed 2month 4d 4h 37min 18.663s CPU time, 14.5G memory peak, 0B memory swap peak.



```

**Comment by cvdbmc** [comment]
What is the point of an alerting and notification feature if you can't send out the notification?
Seems that both SES and SNS don't work. plain SMTP is also not very useful now, so does this mean the only WORKING path for notifications is SMS?

Why is this issue not seen as urgent? Is there another way to send notification that I missed?
